library(knitr)
library(rvest)
library(gsubfn)
library(reshape2)
library(shiny)
require(ggplot2)
require(dplyr)
require(tidyr)
require(readr)
library(rvest)
library(gsubfn)
library(readr)
library(dplyr)
library(XML)
library(readxl)
library(gsubfn)
library(dplyr)
library(XML)


# Uvozimo funkcije za pobiranje in uvoz zemljevida.
source("lib/uvozi.zemljevid.r", encoding="UTF-8")
